-- MySQL Script generated by MySQL Workbench
-- Thu May  4 19:21:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd` DEFAULT CHARACTER SET utf8 ;
USE `bd` ;

-- -----------------------------------------------------
-- Table `bd`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`Empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`Cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`Cuentas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`Periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`Periodos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `idCuenta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idEmpresa_idx` (`idEmpresa` ASC),
  INDEX `idCuenta_idx` (`idCuenta` ASC),
  CONSTRAINT `idEmpresa`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `bd`.`Empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCuenta`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `bd`.`Cuentas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
